version: "3"

services:
  php:
    build:
      context: ./bin/php
    container_name: "php"
    restart: "always"
    networks:
      - backend
    volumes:
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      # - ./config/php/php-ok.ini:/usr/local/etc/php/php-ok.ini
  apache:
    build:
      context: ./bin/apache
    container_name: "apache"
    restart: "always"
    ports:
      - "8099:80"
    networks:
      - frontend
      - backend
    volumes:
      - ./www:/var/www/html
      - ./config/vhosts/httpd.conf:/usr/local/apache2/conf/httpd.conf
      # - ./config/vhosts:/etc/apache2/sites-enabled
      # - ./logs/apache2:/var/log/apache2
  mysql:
    build:
      context: ./bin/mysql
    container_name: "mysql"
    restart: "always"
    volumes:
      # - ./logs/mysql:/var/log/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./dump/CreateTable.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
networks:
  backend:
  frontend: