version: "2"

services:
  php:
    build:
      context: ./bin/php
    restart: "always"
    networks:
      - backend
    volumes:
      - ./www:/var/www/html
  apache:
    build:
      context: ./bin/apache
    restart: "always"
    ports:
      - "8099:80"
    networks:
      - frontend
      - backend
    volumes:
      - ./www:/var/www/html
  mysql:
    build:
      context: ./bin/mysql
    restart: "always"
    volumes:
      - ./dump/CreateTable.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
networks:
  backend:
  frontend: